name: sdist

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build_sdist:
    runs-on: ubuntu-20.04
    outputs:
      VERSION: ${{ steps.build_sdist.outputs.version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, macos-11, windows-2022 ]
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Build sdist
      id: build_sdist
      run: |
        pip install build
        python -m build -s
        VERSION="$(python setup.py --version)"
        echo "version=${VERSION}" | tee -a $GITHUB_OUTPUT

    - name: Upload sdist
      uses: actions/upload-artifact@v3
      with:
        path: dist/mlir-python-utils-*.tar.gz
        name: build_artifact

  upload_sdist:

    name: Upload sdist

    needs: [build_sdist]

    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/download-artifact@v3
        with:
          # unpacks default artifact into dist/
          # if `name: artifact` is omitted, the action will create extra parent dir
          name: build_artifact
          path: dist

      - name: Set up a release page
        id: setup_release
        run: |
          VERSION=${{ needs.build_sdist.outputs.version }}
          echo "`mlir-python-utils` $VERSION distribution created at $(date)" > body.md
          echo "tag_name=${VERSION}" | tee -a $GITHUB_OUTPUT
          echo "release_title=mlir-python-utils-${VERSION}" | tee -a $GITHUB_OUTPUT

      - name: Release current commit
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "dist/*.tar.gz,dist/*.zip"
          bodyFile: body.md
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ steps.setup_release.outputs.tag_name }}"
          name: "${{ steps.setup_release.outputs.release_title }}"
          removeArtifacts: false
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: true

      - name: Release current commit
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "dist/*.tar.gz,dist/*.zip"
          bodyFile: body.md
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "latest"
          name: "latest"
          removeArtifacts: false
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: true

      - name: Release current commit
        uses: ncipollo/release-action@v1.12.0
        with:
          owner: makslevental
          repo: wheels
          artifacts: "dist/*.tar.gz,dist/*.zip"
          token: "${{ secrets.WHEELS_REPO }}"
          tag: "i"
          name: "i"
          removeArtifacts: false
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: true
